// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function CalculateSubnet(arg1:string):Promise<services.Result>;

export function CompareText(arg1:string,arg2:string):Promise<services.Result>;

export function CompressJSON(arg1:string):Promise<services.Result>;

export function ConvertBase(arg1:string,arg2:number):Promise<services.Result>;

export function DateToUnix(arg1:string):Promise<services.Result>;

export function DecodeBase64(arg1:string,arg2:boolean):Promise<services.Result>;

export function EncodeBase64(arg1:string,arg2:boolean):Promise<services.Result>;

export function FormatJSON(arg1:string,arg2:string):Promise<services.Result>;

export function FormatSQL(arg1:string):Promise<services.Result>;

export function GeneratePasswords(arg1:services.PasswordOptions):Promise<services.Result>;

export function JSONToYAML(arg1:string):Promise<services.Result>;

export function MinifySQL(arg1:string):Promise<services.Result>;

export function ParseURL(arg1:string):Promise<services.Result>;

export function QueryDecode(arg1:string):Promise<services.Result>;

export function QueryEncode(arg1:string):Promise<services.Result>;

export function RemoveDuplicate(arg1:string,arg2:services.RemoveDuplicateOptions):Promise<services.Result>;

export function SortLines(arg1:string,arg2:services.SortLinesOptions):Promise<services.Result>;

export function SplitSubnet(arg1:string,arg2:number):Promise<services.Result>;

export function URLDecode(arg1:string):Promise<services.Result>;

export function URLEncode(arg1:string):Promise<services.Result>;

export function UnixToDate(arg1:string,arg2:string,arg3:boolean):Promise<services.Result>;

export function ValidateJSON(arg1:string):Promise<services.Result>;

export function YAMLToJSON(arg1:string):Promise<services.Result>;

export function YAMLToJSONCompact(arg1:string):Promise<services.Result>;
