// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateSubnet(arg1) {
  return window['go']['main']['App']['CalculateSubnet'](arg1);
}

export function CompareText(arg1, arg2) {
  return window['go']['main']['App']['CompareText'](arg1, arg2);
}

export function CompressJSON(arg1) {
  return window['go']['main']['App']['CompressJSON'](arg1);
}

export function ConvertBase(arg1, arg2) {
  return window['go']['main']['App']['ConvertBase'](arg1, arg2);
}

export function DateToUnix(arg1) {
  return window['go']['main']['App']['DateToUnix'](arg1);
}

export function DecodeBase64(arg1, arg2) {
  return window['go']['main']['App']['DecodeBase64'](arg1, arg2);
}

export function EncodeBase64(arg1, arg2) {
  return window['go']['main']['App']['EncodeBase64'](arg1, arg2);
}

export function FormatJSON(arg1, arg2) {
  return window['go']['main']['App']['FormatJSON'](arg1, arg2);
}

export function FormatSQL(arg1) {
  return window['go']['main']['App']['FormatSQL'](arg1);
}

export function GeneratePasswords(arg1) {
  return window['go']['main']['App']['GeneratePasswords'](arg1);
}

export function JSONToYAML(arg1) {
  return window['go']['main']['App']['JSONToYAML'](arg1);
}

export function MinifySQL(arg1) {
  return window['go']['main']['App']['MinifySQL'](arg1);
}

export function ParseURL(arg1) {
  return window['go']['main']['App']['ParseURL'](arg1);
}

export function QueryDecode(arg1) {
  return window['go']['main']['App']['QueryDecode'](arg1);
}

export function QueryEncode(arg1) {
  return window['go']['main']['App']['QueryEncode'](arg1);
}

export function RemoveDuplicate(arg1, arg2) {
  return window['go']['main']['App']['RemoveDuplicate'](arg1, arg2);
}

export function SortLines(arg1, arg2) {
  return window['go']['main']['App']['SortLines'](arg1, arg2);
}

export function SplitSubnet(arg1, arg2) {
  return window['go']['main']['App']['SplitSubnet'](arg1, arg2);
}

export function URLDecode(arg1) {
  return window['go']['main']['App']['URLDecode'](arg1);
}

export function URLEncode(arg1) {
  return window['go']['main']['App']['URLEncode'](arg1);
}

export function UnixToDate(arg1, arg2, arg3) {
  return window['go']['main']['App']['UnixToDate'](arg1, arg2, arg3);
}

export function ValidateJSON(arg1) {
  return window['go']['main']['App']['ValidateJSON'](arg1);
}

export function YAMLToJSON(arg1) {
  return window['go']['main']['App']['YAMLToJSON'](arg1);
}

export function YAMLToJSONCompact(arg1) {
  return window['go']['main']['App']['YAMLToJSONCompact'](arg1);
}
